### PR TITLE
parameter validate

### PR DESCRIPTION
**Pull request by WalterJia**
parameter is not validated in the following code, it will cause crash when user input does not include "=" mark.
 [>] Enter any extra msfvenom options (syntax: OPTION1=value1 or -OPTION2=value2): a a

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
That's a good catch that it is not checking for it.  Rather than doing a new import for strings, could you modify it to if "=" in xtra_opt?

Once that gets changed, I'll test and then merge.  Thanks!

**Comment by ChrisTruncer** [comment]
You have a chance to look at this?

**Comment by WalterJia** [comment]
I will update it today, sorry to delay, thanks.

**Comment by veil-evasion** [comment]
No worries,

Thanks!


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On July 19, 2016 at 6:56:33 PM, WalterJia (notifications@github.com) wrote:

I will update it today, sorry to delay, thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/pull/373#issuecomment-233714078>,
or mute the thread

**Comment by WalterJia** [comment]
have updated it, please merge it, thanks.

**Comment by ChrisTruncer** [comment]
OK, it's merged in.  I cleaned it up a tiny bit post-merge to convert the tabs to spaces and fix indentation, but all looks good.  Thanks!

**Pull request merged**
