### PR TITLE
Fix mix case 'set' & add option 'options'

### PR DESCRIPTION
**Pull request by g0tmi1k**
+ Fix for 4d6eb5167ae2a51fb9050432cb678becc404320a
  + It wasn't working with mixed cased
+ Add 'options' to show information about current set values.

```
 [>] Please enter a command: set lHost 127.0.0.1
 [i] LHOST => 127.0.0.1
 [>] Please enter a command: options

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 LHOST           	127.0.0.1	IP of the metasploit handler
 LPORT           	        	Port of the metasploit handler
 compile_to_exe  	Y       	Compile to an executable

 [>] Please enter a command: set lPOrT 443
 [i] LPORT => 443
 [>] Please enter a command: options

 Required Options:

 Name			Current Value	Description
 ----			-------------	-----------
 LHOST           	127.0.0.1	IP of the metasploit handler
 LPORT           	443     	Port of the metasploit handler
 compile_to_exe  	Y       	Compile to an executable

 [>] Please enter a command:
```

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
It looks like this works for LHOST and LPORT, but when I change the value of other options, it always returns "invalid option".  For example, try changing the "use_pyherion" parameter to Y, or "expire_payload" to 10.  Anything other than LHOST and LPORT it seems to now say is invalid.

**Comment by g0tmi1k** [comment]
My next commit should fix this =).

+ All options are now uppercase.
  + `LHOST` (uppercase) vs `compile_to_exe` (lowercase). _Doesn't make sense to have two formats._
+ All options use same names/values.
  + `ORIG_EXE` vs `ORIGINAL_EXE`. They are both the same, just labeled differently. _Doesn't make sense to have multiple formats._
+ All payloads have a default port (`LPORT`)
  + Some had a default value, others were blank. All have got a value now. _Doesn't make sense for some to have it & not others_
+ Any options which were multiple words are separated now with a underscore
  + `BEACONSECONDS` -> `BEACON_SECONDS`. _Doesn't make sense to have two formats._

**Comment by ChrisTruncer** [comment]
This looks awesome.  Tested it all and it looks good so far.  Only thing is I merged one of your changes in, and it looks like there's some conflicts with this.  Once it's set to go, I'll get it merged in.

**Comment by g0tmi1k** [comment]
**think** I fixed it...

**Comment by ChrisTruncer** [comment]
Sweet, thanks!

**Pull request merged**
