### PR TITLE
Proxy Support and Fixes

### PR DESCRIPTION
**Pull request by killswitch-GUI**
[* ]Additions: 
-Added Urlibs auto proxy population. using urllib2.ProxyHandler.
[*] Small Fixes
-Fixed Try / Except statement, to fix crash on unsuccessful URL request
-Added Randomization to Opener Variables, previously static
-Added some Commits for future refs
-Space Fixes

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, can you check if this works against authenticated proxies too? :)

**Comment by ChrisTruncer** [comment]
You ever check this?

**Comment by killswitch-GUI** [comment]
Yes I tested.

Currently at this point python doesn’t support the ability to gather the CredentialCache and properly authenticate, only perform simple Basic Auth with no credentials and just forward the request to correct location according to static or proxy assessment locations (Registry, ex). 

I am working on being able to access the IWA the same way .NET dose using powershell and as well how IE dose. Can we keep this open for a bit?

**Comment by ChrisTruncer** [comment]
I can get this merged in now based off of what's in it, and then you can look to add in authentication in a later pull request.  Or we can leave this open until you get the other changes added in.  Let me know your thoughts.

**Comment by ChrisTruncer** [comment]
still working on this?

**Comment by killswitch-GUI** [comment]
Yes me and Rohan are going to move over WinHTTP over into Python. This will be a major move as there currently is no way to grab default creds being used by the IWA

**Comment by veil-evasion** [comment]
Ok,

Should this be closed and re-opened once moved over?  What makes most sense to you?

**Comment by killswitch-GUI** [comment]
Yea lets close this out and we will re-open when the code is ready that way this isn't sitting open

**Pull request closed without merging**
