### PR TITLE
New powershell reverse http payload that mimics IE user-agent string

### PR DESCRIPTION
**Pull request by pyrohaz4good**
This is for those times when you manage to bypass AV using veil, but then it turns out the user-agent string is blacklisted by network proxies. This payload first creates a hidden internet explorer instance, navigates to handler and sends an ECHOUA request. The metasploit handler reverse_http will then respond with the user agent of the client visiting the page. This user-agent string is then used to establish the meterpreter connection, the whole time appearing to be normal browsing activity.

**Note: this payload is obviously dependent upon MSF accepting my pull request. In the mean-time, you can check my fork of MSF for the revised handler.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Awesome, thanks a lot for working on this, and then submitting it to us!  It's definitely appreciated.  It'll be great if MSF guys do accept it.  We'll be able to get this merged in once they do (so payload works).

One other option that could also be looked into (if for some reason they don't accept the pull), is this payload (or any of them) could contain maybe 20 different random user agents of legit browsers, and then randomly select one of them to use at the time of generation of the payload.

**Comment by pyrohaz4good** [comment]
My pull request to MSF is submitted. I'll let you know when MSF accepts it. Comments I got were positive and it looks like it'll go through.

**Comment by ChrisTruncer** [comment]
You ever get your request merged into metasploit?

**Comment by pyrohaz4good** [comment]
I actually got a note a few days back saying they are working on the merge
now. I got rolled into a refractering on the meterpreter handlers so it
should be any day now.

**Comment by ChrisTruncer** [comment]
I'm going to go ahead and close this out for now.  If/when you get it added in to metasploit, please definitely submit this pull request again!

**Pull request closed without merging**
