### PR TITLE
Add support for Fedora 22+ to setup

### PR DESCRIPTION
**Pull request by gordonrs**
Added support in for Fedora 22 so I can use it on my own setup without requiring Debian/Ubuntu. So far, I've only tested it with Fedora 22, but the beginnings are there to have it work with CentOS and RHEL. I would have to do testing on it first before I add those to the version checks.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Thanks for sending this over!

**Comment by ChrisTruncer** [comment]
Everything looks good Kali wise, I don't currently have a fedora 22+ system to test on, so I'll take your word for this.  Hopefully if it doesn't work, then you or someone else can submit a patch.  But otherwise, thanks for sending this over!

**Comment by gordonrs** [comment]
My pleasure in sending it! If there's any issues brought up as a result of the PR for other users, I'll be more than happy to correct them.

**Comment by veil-evasion** [comment]
Awesome, thanks!!!

**Pull request merged**
