### PR TITLE
- Added a bind_tcp python meterpreter module

### PR DESCRIPTION
**Pull request by m1m1x**
I just added a new module : python/meterpreter/bind_tcp based on the existing reverse_tcp one.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Thanks for the submission!  I just tested it out, and everything works perfectly!

If I don't get this merged in tomorrow, then I believe I should be able to get this merged in on Monday.  We appreciate you sending this in, awesome work!

**Comment by m1m1x** [comment]
Hi,

I just added a basic support to generate 64 bits python payloads.
For now, it only support pyinstaller and a few python payloads but i'll patch the remaining payloads and work on py2exe if you find this interesting.

**Comment by secretsquirrel** [comment]
Yeah. That's a would be great feature.  x64 AV detects very little.


On Feb 1, 2015, at 10:29 AM, mimix <notifications@github.com> wrote:

Hi,

I just added a basic support to generate 64 bits python payloads.
For now, it only support pyinstaller and a few python payloads but i'll
patch the remaining payloads and work on py2exe if you find this
interesting.

—
Reply to this email directly or view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/pull/99#issuecomment-72369237>
.

**Comment by ChrisTruncer** [comment]
I'll have to get playing with this.  I believe pyinstaller creates a binary of the same architecture that it is operating in.  I'll test out your latest pushes, ideally soon (sorry, on travel and been busy.  Been meaning to get looking at this and play with it).  But this looks like awesome work, so thanks again for working on this.  Definitely haven't forgotten about it and hope to get it merged in shortly

**Comment by m1m1x** [comment]
Hi,
If i got it right, pyinstaller create a binary of the same architecture of the python.exe process that runs it. So you have to launch a x64 python.exe process within a wine64 instance to get a 64bits binary.
No worries for the delay, I'm still working on other ideas :)
Let me know if something is wrong, i'll be happy to help.

**Comment by ChrisTruncer** [comment]
I'm playing with the module now, and works perfect (haven't tested x64 yet).  Everything works great on that end so far module wise, so it looks awesome :).  I did have some requests to look into:

For the payload, could you change the required option of "lhost" to "rhost" since it is a bind payload (to reflect how metasploit handles the same situation).

Also, Evasion generates a handler resource file for metasploit that lets someone "batch" setup a metasploit handler.  Currently, it's creating a handler file for a reverse payload vs. bind.

Those are the only two comments I have so far.  I'll stand up a VM to test x64 soon, and only potential upcoming request would be for the handler to be able to recognize when x64 payload is used, and generating the corresponding x64 handler file.

I hope that helps some, let me know if I need to clarify anything.

Thanks again!

**Comment by m1m1x** [comment]
Hi Chris,

I took care of your remarks in the last commit.
However, in order to get the bind_tcp handler to work, you have to fill RHOST with a reachable ip address from the msfconsole (ie : not 0.0.0.0).

In order to get 64bits payload to work, setup.sh must be relaunched and a new file should be hosted at https://www.veil-framework.com/InstallMe/requiredfiles_x64.zip .
This archive has to contain two files : 
- python-2.7.9.amd64.msi (https://www.python.org/ftp/python/2.7.9/python-2.7.9.amd64.msi)
- pywin32-219.win-amd64-py2.7.exe (http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/)

**Comment by ChrisTruncer** [comment]
Yeah, I see what you mean.  I believe that I was wrong.  I thought it said "LHOST" for the option that is needed when generating the payload vs. "RHOST", but I think it may have actually been RHOST all along.

Anyways.  This payload works great for me and I'm not running into any conflicts.  This was really nice work.  I'm going to try to get either @themightyshiv or @HarmJ0y to sign off on it too and then we'll get it merged in.

**Comment by ChrisTruncer** [comment]
Hey again,

Still don't want you to think we forgot about this.  I was about to merge this in, and it looks like a metasploit update broke compatibility with Veil-Evasion.  We're trying to hunt down the cause and fix it, and once that is fixed, then get this merged in.

**Comment by ChrisTruncer** [comment]
Figured everything out.  Thanks for submitting this!  We'll be calling it out for our V-Day

**Comment by ChrisTruncer** [comment]
merged

**Comment by m1m1x** [comment]
Thanks Chris :)

**Pull request merged**
