### PR TITLE
Display full path to file

### PR DESCRIPTION
**Pull request by g0tmi1k**
Rather than displaying the local/relative path - it will display the full path (useful for Kali-Linux users who have it installed). 

...Started to error number codes, making it easier to debug/understand where the issue is.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
This looks good so far, the only thing I noticed is that in the event an issue is discovered (which triggers the code to display the full path), it also triggers the auto-running of the setup script.  Do you want to leave that in there?  I believe you had removed a lot of the auto-running of the script.

**Comment by g0tmi1k** [comment]
Good idea. =)
Disabled auto running setup.sh.

**Comment by ChrisTruncer** [comment]
Ah, same thing here.  I just merged one of your other PRs, and now it looks like this has some merge conflicts.  If you want, are you able to get this updated?  Once it is, I believe this should be good to merge.

**Comment by g0tmi1k** [comment]
**think** I've fixed this - even if it was with a bit of force (-f)... _sorry_.

**Comment by ChrisTruncer** [comment]
Thanks!  Merged

**Pull request merged**
