### PR TITLE
Some minor chages/fixes while insomnia kept me up for several days barring a small bit of time here and there

### PR DESCRIPTION
**Pull request by opticshade**
Update to Pyinstaller breaks things due to some libraries being linked against msvcrt100.dll and Veil is still using msvcrt90.dll. This issue only crops up when running 32bit code on an x64 system. Fix was to use a dev branch. Some minor installer patches that will help people not installing as root or running on a system other than kali. I have only tested on Fedora 24. I saw some todos in a few files that I went and changed since they were easy enough. Fair warning this was done under moderate sleep deprivation so definately needs some review but most of my tests were successful save for an issue reverse_https python payloads crashing which I have no clue about how to fix right now. I've never messed with Pyinstaller before. Theree were a few bugs caused by the random imports and I removed the offending header files from the list. Might be some more things but my memory of the past few days is a bit of a blur.

Hope this can help in someway.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Thanks for sending this over.  This is obviously going to take some time to process and review, but thanks for the contribution!

**Comment by ChrisTruncer** [comment]
I wanted to let you know I did see this.

**Comment by opticshade** [comment]
Hey no problem glad I could help!

**Comment by opticshade** [comment]
Let me know if you see anything needs changes as I said moderate sleep deprivation was my state of mind at the time.

**Comment by ChrisTruncer** [comment]
Just a heads up, that this is being closed since Veil-Evasion is no longer the supported version of Veil (the veil 3.0 repo is). THanks for your contribution!

**Pull request closed without merging**
