### PR TITLE
Added a rev_ssh.py module, changed default encoder back to shikata_ga_nai

### PR DESCRIPTION
**Pull request by byt3bl33d3r**
This PR adds a rev_ssh.py module which is a port of https://github.com/trustedsec/meterssh for veil-evasion,
for the payload to compile I had to install the Paramiko and ecdsa python libraries.
Additionally I changed the default encoder for msfvenom to shikata_ga_nai, don't know if that might break any payloads though.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Have you had the chance to work on this?

**Comment by byt3bl33d3r** [comment]
@ChrisTruncer I have now!  really sorry this took so long but life got in the way :P take a look and let me know if i need to change anything

**Comment by ChrisTruncer** [comment]
I'm getting a couple errors when running this.  The first one is that main is referenced before use, might need to add a main = '' before it.  Even with that addition, it looks like I still had an error:

TypeError: not all arguments converted during string formatting

**Comment by byt3bl33d3r** [comment]
@ChrisTruncer ok should have fixed everything

**Comment by lev3lz** [comment]
rev_ssh.py is really great.. suggest getting a way to seal it in a way so that it isnt using bind on the localhost... ?

**Comment by ChrisTruncer** [comment]
You ever figure this out on how to get the dependencies installed by chance?

**Comment by byt3bl33d3r** [comment]
@ChrisTruncer frankly I don't remember, will try agains later today :P

**Comment by ChrisTruncer** [comment]
cool :)

**Comment by byt3bl33d3r** [comment]
@ChrisTruncer ok so I got it working (will put a step by step guide in the PR description this time for the deps), I also have a couple of more PR's on the way ! 
I'm going to close this one since I messed up my fork by accident and submit them all when their ready

**Pull request closed without merging**
