### PR TITLE
include parrot support

### PR DESCRIPTION
**Pull request by EclipseSpark**

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
So, I don't mind getting this merged in to make it easier to install on Parrot, but it will not be a distro that we officially support.  @gordonrs - would you agree with this?

**Comment by EclipseSpark** [comment]
i'll be happy to maintain the compatibility with parrot up-to-date (no additional work for you)

**Comment by dumbo0** [comment]
ChrisTruncer , rdpy-rdpclient.py doesn.t connect if the guy have this:  Alow connections only from computers running Remote Desktop with network Level Auth.(more secure) , exist there a solution? thanks

**Comment by ChrisTruncer** [comment]
OK, merged.

Thanks!

**Pull request merged**
