### PR TITLE
Add colour to setup.sh

### PR DESCRIPTION
**Pull request by g0tmi1k**
+ Add a splash of colour to `setup.sh`
+ Updates for kali 2/rolling

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Hey, not sure if the call order was slightly moved around, but I can't install python currently because wine may not be there? I manually installed it to test/troubleshoot, but I'm getting a lot of errors.  (These errors aren't from your script, but something going on with Kali rolling).

python

go issues

Not sure why, but I'm running into both of these problems when trying to install veil on Kali x64 rolling.

It might be because I don't have wine-bin:i386 installed.  But I've tried using a lot of different mirrors, and I can't get a mirror which has that.

**Comment by g0tmi1k** [comment]
The order hasn't been moved about.

It should not be using `wine-bin:i386` at all any more.

I don't get the python errors.

Go also doesn't work for me - thats why the kali-package has a pre-built version of Go when you do apt-get install veil....

**Comment by ChrisTruncer** [comment]
Hm, do you know what version of wine it should be using now?  I'm testing on a clean install of kali x64 rolling and running this setup script.  The python stuff seems to fail.  Not sure if it's because of any other changes to the OS?

But for now, i can't seem to get this installed at all (with either mine or your script).

The only way I can get this likely working is to remove all native compilation within Kali, but that's a major strength IMO and would require another Windows VM/extra time.

**Comment by ChrisTruncer** [comment]
Not sure at the moment the best route forward

**Comment by g0tmi1k** [comment]
Looks like the Go bug is a 1.4.x thing. Upgraded to 1.5.2.

No idea how you got those python issues. Not doing it for me (kali-rolling 2016.1 x64 VMware)

**Comment by ChrisTruncer** [comment]
You, good sir, are awesome.  Everything is now working for me.  I'm not sure what the problem was on the python side, I basically just re-downloaded a new iso, built a new VM, and then that whole process just started working for me again.

Everything is really well done, and working.  I can't thank you enough for your help with this.  

If we meet at some point, I owe beers :)

**Comment by g0tmi1k** [comment]
:tada: :balloon: :birthday: 
Glad to know its working for you!

Not a problem. Glad I've helped out ;)

**Pull request merged**
