### PR TITLE
Fix size issue in go rev tcp

### PR DESCRIPTION
**Pull request by b00stfr3ak**
This pr will fix the issue in https://github.com/Veil-Framework/Veil-Evasion/issues/391

### CODE REVIEW

**Comment by b00stfr3ak** [comment]
Before and after the fix.

2__docker_run_--rm_-it_-v___pwd___tmp__-p_8080_8080_metasploit_cli_sh__docker_

**Comment by ChrisTruncer** [comment]
Should I test #443 first before this?  When I try to compile this in Veil I am getting errors where it states:

gotest.go:24: missing value in const declaration
gotest.go:24: syntax error: unexpected literal 1000 at end of statement

**Comment by ChrisTruncer** [comment]
I've also tried running just the source code on Windows with Golang installed, and am encountering the above error.

**Comment by ChrisTruncer** [comment]
Here's the link to the source code it output - http://pastebin.com/y0N4jCt8

**Comment by b00stfr3ak** [comment]
Sorry, missed a =

**Comment by ChrisTruncer** [comment]
I'm still encountering an issue, where msf says it is sending the stage (dll) over the network, but the session is still never established.

nosession

I'll try to test on a different system/VMs and see if it works there.  If it does, then it's isolated to my machines.

**Comment by ChrisTruncer** [comment]
I can see the executable, and it never crashes.  I've also run just the script with go run, and it runs, never crashes either.  But the session still just doesn't establish oddly enough.

**Comment by b00stfr3ak** [comment]
That's strange. Is there an error now? I didn't see one in your screenshot.

GOOS=windows GOARCH=386 go build -ldflags -H=windowsgui -v -o payload.exe is how I compile the file in the pastebin link you posted earlier. 

2__docker_run_--rm_-it_-v___pwd___tmp__-p_8080_8080_metasploit_cli_sh__docker_

**Comment by ChrisTruncer** [comment]
That's really odd.  I am running Windows 10 in this VM, I will have to try a WIndows 7 and test that out.  I did just compile it with the same command line args, and it still starts to send the stage, but no session is established.

No errors at all, the payload just keeps running, but doesn't error out until I quit it.  Same with running from source

**Comment by ChrisTruncer** [comment]
Not sure if it is a WIndows 10 thing, but I will be sure to test that.

**Comment by b00stfr3ak** [comment]
Yeah, that would be interesting. Maybe compile with 

GOOS=windows GOARCH=386 go build -v -o payload.exe

To see if the console throws any errors.

**Comment by ChrisTruncer** [comment]
OK, I just grabbed a Win 7 VM and it works.  So it's isolated to either my windows VM, or Windows 10

**Comment by ChrisTruncer** [comment]
Merging this in, but this would be interesting to figure out the problem with Win 10.

Thanks for all your help

**Pull request merged**
